import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    // {
    //   name: 'Free Shirt',
    //   slug: 'free-shirt',
    //   category: 'Shirts',
    //   image: '/images/shirt1.jpg',
    //   price: 70,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popular shirt',
    // },
    // {
    //   name: 'Fit Shirt',
    //   slug: 'fit-shirt',
    //   category: 'Shirts',
    //   image: '/images/shirt2.jpg',
    //   price: 80,
    //   brand: 'Adidas',
    //   rating: 4.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popular shirt',
    // },
    // {
    //   name: 'Slim Shirt',
    //   slug: 'slim-shirt',
    //   category: 'Shirts',
    //   image: '/images/shirt3.jpg',
    //   price: 90,
    //   brand: 'Raymond',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popular shirt',
    // },
    // {
    //   name: 'Golf Pants',
    //   slug: 'golf-pants',
    //   category: 'Pants',
    //   image: '/images/pants1.jpg',
    //   price: 90,
    //   brand: 'Oliver',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'Smart looking pants',
    // },
    // {
    //   name: 'Fit Pants',
    //   slug: 'fit-pants',
    //   category: 'Pants',
    //   image: '/images/pants2.jpg',
    //   price: 95,
    //   brand: 'Zara',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popular pants',
    // },
    // {
    //   name: 'Classic Pants',
    //   slug: 'classic-pants',
    //   category: 'Pants',
    //   image: '/images/pants3.jpg',
    //   price: 75,
    //   brand: 'Casely',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 0,
    //   description: 'A popular pants',
    // },
    {
      name: 'E-Bike VANARA',
      slug: 'E-Bike Vanara',
      category: 'Bike',
      image: '/images/products/product (1).png',
      price: 1182.2,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
    {
      name: 'E-Bike LADY VANARA ',
      slug: 'E-Bike LADY VANARA ',
      category: 'Bike',
      image: '/images/products/product (2).png',
      price: 1182.2,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
    {
      name: 'E-Bike CIRKIT LV',
      slug: 'E-Bike CIRKIT LV',
      category: 'Bike',
      image: '/images/products/product (3).png',
      price: 1688.77,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
    {
      name: 'E-Bike SEMAR',
      slug: 'E-Bike SEMAR',
      category: 'Bike',
      image: '/images/products/product (4).png',
      price: 3377.53,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
    {
      name: 'Sepeda Listrik (Model A)',
      slug: 'Sepeda Listrik (Model A)',
      category: 'Bike',
      image: '/images/products/product (5).png',
      price: 1351.01,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
    {
      name: 'Sepeda Listrik (Model B)',
      slug: 'Sepeda Listrik (Model B)',
      category: 'Bike',
      image: '/images/products/product (6).png',
      price: 1351.01,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
    {
      name: 'Sepeda Listrik (Model C)',
      slug: 'Sepeda Listrik (Model C)',
      category: 'Bike',
      image: '/images/products/product (7).png',
      price: 1351.01,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
    {
      name: 'Sepeda Motor Listrik',
      slug: 'Sepeda Motor Listrik',
      category: 'Bike',
      image: '/images/products/product (8).png',
      price: 1688.77,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
    {
      name: 'Motor Listrik 3 Roda Gerobak Sampah',
      slug: 'Motor Listrik 3 Roda Gerobak Sampah',
      category: 'Bike',
      image: '/images/products/product (9).png',
      price: 3715.29,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
    {
      name: 'Sepeda Listrik NgebUTS (Maras)',
      slug: 'Sepeda Listrik NgebUTS (Maras)',
      category: 'Bike',
      image: '/images/products/product (10).png',
      price: 1283.46,
      brand: 'Brida',
      rating: 4.5,
      numReviews: 10,
      countInStock: 9,
      description:
        'Daya Angkut : 100 Kg , Kecepatan , Maksimal : 35 Km / Jam , Jarak Tempuh : 40 Km / Sekali Charger Full , Waktu Pengisian : 4 - 6 Jam , Tipe Dinamo : BLDC 350W, Controller : 48V / 15A , Charger : 48V / 2A , Baterai : Lithium Ion 48 V / 12 Ah , Sistem Rem Depan : Hydraulic Disc. 160 , Sistem Rem , Belakang : Hydraulic Disc. 160 , Roda Depan : Fatbike 20x4.0 , Roda Belakang : Fatbike 20x4.0 , Rangka : Cromoly , No. Uji Tipe : , ',
    },
  ],
};
export default data;
